services:
  frontend:
    build:
      context: ./web4/frontend
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    restart: unless-stopped
  
  backend:
    build:
      context: ./web4/backend
      dockerfile: Dockerfile
    ports:
      - "4445:4445"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studs
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: