# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/widgets/_source/input.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 597)
        Form.setStyleSheet("")
        self.upload_from_file = QtWidgets.QPushButton(Form)
        self.upload_from_file.setGeometry(QtCore.QRect(410, 560, 201, 29))
        self.upload_from_file.setStyleSheet("QPushButton {\n"
"    font: 11pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E1E1E;\n"
"}")
        self.upload_from_file.setObjectName("upload_from_file")
        self.matrix_box = QtWidgets.QGroupBox(Form)
        self.matrix_box.setGeometry(QtCore.QRect(10, 10, 601, 542))
        self.matrix_box.setStyleSheet("")
        self.matrix_box.setTitle("")
        self.matrix_box.setObjectName("matrix_box")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(215, 558, 144, 31))
        self.groupBox_2.setStyleSheet("border: none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.slider = QtWidgets.QSlider(self.groupBox_2)
        self.slider.setGeometry(QtCore.QRect(10, 0, 125, 30))
        self.slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: #444;  /* Темный фон полосы */\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #9C27B0;  /* Фиолетовый ползунок */\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -4px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #AB47BC;  /* Светлый фиолетовый при наведении */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #BA68C8; /* Светло-фиолетовая заполненная часть */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #777; /* Темный серый незаполненной части */\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.slider.setMinimum(1)
        self.slider.setMaximum(20)
        self.slider.setPageStep(1)
        self.slider.setTracking(True)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.slider_value = QtWidgets.QLineEdit(Form)
        self.slider_value.setGeometry(QtCore.QRect(360, 560, 41, 27))
        self.slider_value.setStyleSheet("border: none;\n"
"font: 11pt \"Consolas\";")
        self.slider_value.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_value.setReadOnly(True)
        self.slider_value.setObjectName("slider_value")
        self.accuracy_line = QtWidgets.QLineEdit(Form)
        self.accuracy_line.setGeometry(QtCore.QRect(10, 560, 201, 28))
        self.accuracy_line.setStyleSheet("font: 10pt \"Consolas\";")
        self.accuracy_line.setMaxLength(10)
        self.accuracy_line.setAlignment(QtCore.Qt.AlignCenter)
        self.accuracy_line.setObjectName("accuracy_line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.upload_from_file.setText(_translate("Form", "Загрузить из файла"))
        self.slider_value.setText(_translate("Form", "1"))
        self.accuracy_line.setPlaceholderText(_translate("Form", "Введите точность"))
