# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/widgets/_source/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 794)
        MainWindow.setStyleSheet("background-color: #1E1E1E;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(13, 13, 641, 771))
        self.groupBox.setStyleSheet("font: 11pt \"Courier New\";\n"
"background-color: #2D2D30;\n"
"border: 1px solid #C792EA;\n"
"color: #C792EA;")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 13, 621, 41))
        self.label.setStyleSheet("font: 12pt \"Consolas\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.input_widget = QtWidgets.QWidget(self.groupBox)
        self.input_widget.setGeometry(QtCore.QRect(10, 65, 621, 597))
        self.input_widget.setObjectName("input_widget")
        self.clear_input_data = QtWidgets.QPushButton(self.groupBox)
        self.clear_input_data.setGeometry(QtCore.QRect(10, 670, 621, 41))
        self.clear_input_data.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E1E1E;\n"
"}")
        self.clear_input_data.setObjectName("clear_input_data")
        self.start_calculation = QtWidgets.QPushButton(self.groupBox)
        self.start_calculation.setGeometry(QtCore.QRect(10, 720, 621, 41))
        self.start_calculation.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E1E1E;\n"
"}")
        self.start_calculation.setObjectName("start_calculation")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(668, 13, 641, 771))
        self.groupBox_2.setStyleSheet("font: 11pt \"Courier New\";\n"
"background-color: #2D2D30;\n"
"border: 1px solid #C792EA;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 13, 621, 41))
        self.label_2.setStyleSheet("color: #C792EA;\n"
"font: 12pt \"Consolas\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.output_widget = QtWidgets.QWidget(self.groupBox_2)
        self.output_widget.setGeometry(QtCore.QRect(10, 65, 621, 696))
        self.output_widget.setStyleSheet("color: #C792EA;")
        self.output_widget.setObjectName("output_widget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вычислительная Математика. Лабораторная работа 1"))
        self.label.setText(_translate("MainWindow", "Входные данные"))
        self.clear_input_data.setText(_translate("MainWindow", "Очистить ввод"))
        self.start_calculation.setText(_translate("MainWindow", "Запустить расчет"))
        self.label_2.setText(_translate("MainWindow", "Результат"))
