/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly 33.0.1.Final (WildFly Core 25.0.1.Final) - 2.3.15.Final
 * Generated at: 2024-09-29 11:15:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import com.server.Row;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/static/media/graph.svg", Long.valueOf(1727608158000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.server.Row");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private jakarta.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
        throws java.io.IOException, jakarta.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(jakarta.servlet.http.HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/3.1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ru-RU\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Лабораторная работа №2</title>\r\n");
      out.write("    <script src=\"static/js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("    <script defer src=\"static/js/point.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/index.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/jpg\" href=\"static/media/favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"content-container\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header-container\">\r\n");
      out.write("                <div>Пышкин Никита Сергеевич P3213</div>\r\n");
      out.write("                <div></div>\r\n");
      out.write("                <div>409429</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <form action=\"/server/check\" method=\"get\" id=\"form\">\r\n");
      out.write("        <main class=\"main\">\r\n");
      out.write("            <div class=\"main__left-column\">\r\n");
      out.write("                <div class=\"main__block\" id=\"graph-container\">\r\n");
      out.write("                    ");
      out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"-20 -20 440 440\" class=\"graph\" id=\"graph\">\r\n");
      out.write("    <polygon points=\"200,200 370,200 200,285\" fill-opacity=\"0.5\" fill=\"#1638b2\"/>\r\n");
      out.write("    <rect x=\"30\" y=\"30\" width=\"170\" height=\"170\" fill-opacity=\"0.5\" fill=\"#1638b2\"/>\r\n");
      out.write("    <path d=\"M 200 115 A 80 80 0 0 0 115 200 L 200 200\" fill-opacity=\"0.5\" fill=\"#1638b2\" transform=\"rotate(90, 200, 200)\" />\r\n");
      out.write("\r\n");
      out.write("    <line x1=\"0\" y1=\"200\" x2=\"400\" y2=\"200\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"200\" y1=\"0\" x2=\"200\" y2=\"400\" stroke=\"#000000\"/>\r\n");
      out.write("    \r\n");
      out.write("    <line x1=\"370\" y1=\"198\" x2=\"370\" y2=\"202\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"285\" y1=\"198\" x2=\"285\" y2=\"202\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"115\" y1=\"198\" x2=\"115\" y2=\"202\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"30\" y1=\"198\" x2=\"30\" y2=\"202\" stroke=\"#000000\"/>\r\n");
      out.write("\r\n");
      out.write("    <line x1=\"198\" y1=\"30\" x2=\"202\" y2=\"30\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"198\" y1=\"115\" x2=\"202\" y2=\"115\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"198\" y1=\"285\" x2=\"202\" y2=\"285\" stroke=\"#000000\"/>\r\n");
      out.write("    <line x1=\"198\" y1=\"370\" x2=\"202\" y2=\"370\" stroke=\"#000000\"/>\r\n");
      out.write("\r\n");
      out.write("    <polygon points=\"400,200 392,203 392,197\" fill=\"#000000\" stroke=\"#000000\"/>\r\n");
      out.write("    <polygon points=\"200,0 197,8 203,8\" fill=\"#000000\" stroke=\"#000000\"/>\r\n");
      out.write("\r\n");
      out.write("    <text x=\"365\" y=\"190\" style=\"font-family: sans-serif\">R</text>\r\n");
      out.write("    <text x=\"273\" y=\"190\" style=\"font-family: sans-serif\">R/2</text>\r\n");
      out.write("    <text x=\"98\" y=\"190\" style=\"font-family: sans-serif\">-R/2</text>\r\n");
      out.write("    <text x=\"20\" y=\"190\" style=\"font-family: sans-serif\">-R</text>\r\n");
      out.write("    \r\n");
      out.write("    <text x=\"206\" y=\"35\" style=\"font-family: sans-serif\">R</text>\r\n");
      out.write("    <text x=\"206\" y=\"120\" style=\"font-family: sans-serif\">R/2</text>\r\n");
      out.write("    <text x=\"206\" y=\"289\" style=\"font-family: sans-serif\">-R/2</text>\r\n");
      out.write("    <text x=\"206\" y=\"373\" style=\"font-family: sans-serif\">-R</text>\r\n");
      out.write("</svg>");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"main__block\">\r\n");
      out.write("                    <div class=\"row\">Параметры</div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div>Выберете X:</div>\r\n");
      out.write("                        <input name=\"x\" id=\"x-input\" type=\"text\" placeholder=\"значение от -5 до 5\" maxlength=\"7\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div>Выберете Y:</div>\r\n");
      out.write("                        <select name=\"y\" id=\"y-input\">\r\n");
      out.write("                            <option name=\"y\" value=\"-5\">-5</option>\r\n");
      out.write("                            <option name=\"y\" value=\"-4\">-4</option>\r\n");
      out.write("                            <option name=\"y\" value=\"-3\">-3</option>\r\n");
      out.write("                            <option name=\"y\" value=\"-2\">-2</option>\r\n");
      out.write("                            <option name=\"y\" value=\"-1\">-1</option>\r\n");
      out.write("                            <option name=\"y\" value=\"0\">0</option>\r\n");
      out.write("                            <option name=\"y\" value=\"1\">1</option>\r\n");
      out.write("                            <option name=\"y\" value=\"2\">2</option>\r\n");
      out.write("                            <option name=\"y\" value=\"3\">3</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div>Выберете R:</div>\r\n");
      out.write("                        <div><input name=\"r\" type=\"checkbox\" value=\"1\">1</div>\r\n");
      out.write("                        <div><input name=\"r\" type=\"checkbox\" value=\"2\">2</div>\r\n");
      out.write("                        <div><input name=\"r\" type=\"checkbox\" value=\"3\">3</div>\r\n");
      out.write("                        <div><input name=\"r\" type=\"checkbox\" value=\"4\">4</div>\r\n");
      out.write("                        <div><input name=\"r\" type=\"checkbox\" value=\"5\">5</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"main__block submit_button\" style=\"margin-bottom: 15px;\" id=\"submit\">\r\n");
      out.write("                    Проверить\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"result-title\">Результат</div>\r\n");
      out.write("                <div class=\"result-container\">\r\n");
      out.write("                    <div style=\"border-top: 1px solid #000000;\">X</div>\r\n");
      out.write("                    <div style=\"border-top: 1px solid #000000;\">Y</div>\r\n");
      out.write("                    <div style=\"border-top: 1px solid #000000;\">R</div>\r\n");
      out.write("                    <div style=\"border-top: 1px solid #000000;\">Попал?</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"result-container\" id=\"result\">\r\n");
      out.write("                    ");
 if (getServletContext().getAttribute("rows") != null) { 
      out.write("\r\n");
      out.write("                        ");
 ArrayList<Row> array = (ArrayList<Row>) getServletContext().getAttribute("rows");
      out.write("\r\n");
      out.write("                        ");
 for (int index = array.size() - 1; index >= 0; index--) { 
      out.write("\r\n");
      out.write("                            <div>");
      out.print( array.get(index).getX() );
      out.write("</div>\r\n");
      out.write("                            <div>");
      out.print( array.get(index).getY() );
      out.write("</div>\r\n");
      out.write("                            <div>");
      out.print( array.get(index).getR() );
      out.write("</div>\r\n");
      out.write("                            <div>");
      out.print( array.get(index).getResult() ? "<span style='color:green'>Да</span>" : "<span style='color:red'>Нет</span>" );
      out.write("</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        window.onload = function() {\r\n");
      out.write("            loadData();\r\n");
      out.write("        ");
 if (getServletContext().getAttribute("rows") != null) { 
      out.write("\r\n");
      out.write("            ");
 ArrayList<Row> array = (ArrayList<Row>) getServletContext().getAttribute("rows");
      out.write("\r\n");
      out.write("            ");
 for (int index = array.size() - 1; index >= 0; index--) { 
      out.write("\r\n");
      out.write("                drawPoint(\r\n");
      out.write("                    ");
      out.print( array.get(index).getX() );
      out.write(",\r\n");
      out.write("                    ");
      out.print( array.get(index).getY() );
      out.write(",\r\n");
      out.write("                    ");
      out.print( array.get(index).getR() );
      out.write(", \r\n");
      out.write("                    ");
      out.print( array.get(index).getResult() );
      out.write("\r\n");
      out.write("                );\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new jakarta.servlet.ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
